// { dg-do link }
// Generated by overload.py

struct S{};

S s;                         // non-const lvalue
S const cs = s;              // const lvalue
S f() { return S(); }        // non-const rvalue
S const cf() { return S(); } // const rvalue

void l1000(S&) {};

void l0100(const S&) {};

void l1100(S&) {};
void l1100(const S&);

void l0010(S&&) {};

void l1010(S&) {};
void l1010(S&&);

void l0110(const S&) {};
void l0110(S&&);

void l1110(S&) {};
void l1110(const S&);
void l1110(S&&);

void l0001(const S&&) {};

void l1001(S&) {};
void l1001(const S&&);

void l0101(const S&) {};
void l0101(const S&&);

void l1101(S&) {};
void l1101(const S&);
void l1101(const S&&);

void l0011(S&&) {};
void l0011(const S&&);

void l1011(S&) {};
void l1011(S&&);
void l1011(const S&&);

void l0111(const S&) {};
void l0111(S&&);
void l0111(const S&&);

void l1111(S&) {};
void l1111(const S&);
void l1111(S&&);
void l1111(const S&&);

void cl0100(const S&) {};

void cl1100(S&);
void cl1100(const S&) {};

void cl0110(const S&) {};
void cl0110(S&&);

void cl1110(S&);
void cl1110(const S&) {};
void cl1110(S&&);

void cl0001(const S&&) {};

void cl1001(S&);
void cl1001(const S&&) {};

void cl0101(const S&) {};
void cl0101(const S&&);

void cl1101(S&);
void cl1101(const S&) {};
void cl1101(const S&&);

void cl0011(S&&);
void cl0011(const S&&) {};

void cl1011(S&);
void cl1011(S&&);
void cl1011(const S&&) {};

void cl0111(const S&) {};
void cl0111(S&&);
void cl0111(const S&&);

void cl1111(S&);
void cl1111(const S&) {};
void cl1111(S&&);
void cl1111(const S&&);

void r0100(const S&) {};

void r1100(S&);
void r1100(const S&) {};

void r0010(S&&) {};

void r1010(S&);
void r1010(S&&) {};

void r0110(const S&);
void r0110(S&&) {};

void r1110(S&);
void r1110(const S&);
void r1110(S&&) {};

void r0001(const S&&) {};

void r1001(S&);
void r1001(const S&&) {};

void r0101(const S&);
void r0101(const S&&) {};

void r1101(S&);
void r1101(const S&);
void r1101(const S&&) {};

void r0011(S&&) {};
void r0011(const S&&);

void r1011(S&);
void r1011(S&&) {};
void r1011(const S&&);

void r0111(const S&);
void r0111(S&&) {};
void r0111(const S&&);

void r1111(S&);
void r1111(const S&);
void r1111(S&&) {};
void r1111(const S&&);

void cr0100(const S&) {};

void cr1100(S&);
void cr1100(const S&) {};

void cr0110(const S&) {};
void cr0110(S&&);

void cr1110(S&);
void cr1110(const S&) {};
void cr1110(S&&);

void cr0001(const S&&) {};

void cr1001(S&);
void cr1001(const S&&) {};

void cr0101(const S&);
void cr0101(const S&&) {};

void cr1101(S&);
void cr1101(const S&);
void cr1101(const S&&) {};

void cr0011(S&&);
void cr0011(const S&&) {};

void cr1011(S&);
void cr1011(S&&);
void cr1011(const S&&) {};

void cr0111(const S&);
void cr0111(S&&);
void cr0111(const S&&) {};

void cr1111(S&);
void cr1111(const S&);
void cr1111(S&&);
void cr1111(const S&&) {};


int main()
{
  l1000(s);
  l0100(s);
  l1100(s);
  l0010(s);
  l1010(s);
  l0110(s);
  l1110(s);
  l0001(s);
  l1001(s);
  l0101(s);
  l1101(s);
  l0011(s);
  l1011(s);
  l0111(s);
  l1111(s);
  cl0100(cs);
  cl1100(cs);
  cl0110(cs);
  cl1110(cs);
  cl0001(cs);
  cl1001(cs);
  cl0101(cs);
  cl1101(cs);
  cl0011(cs);
  cl1011(cs);
  cl0111(cs);
  cl1111(cs);
  r0100(f());
  r1100(f());
  r0010(f());
  r1010(f());
  r0110(f());
  r1110(f());
  r0001(f());
  r1001(f());
  r0101(f());
  r1101(f());
  r0011(f());
  r1011(f());
  r0111(f());
  r1111(f());
  cr0100(cf());
  cr1100(cf());
  cr0110(cf());
  cr1110(cf());
  cr0001(cf());
  cr1001(cf());
  cr0101(cf());
  cr1101(cf());
  cr0011(cf());
  cr1011(cf());
  cr0111(cf());
  cr1111(cf());

  return 0;
}
